### ISSUE TITLE
use `node::RegisterSignalHandler` to avoid clobbering node's signal handlers

### ISSUE THREAD

**Issue by devsnek** [node-3d/segfault-raub#1]
V8 has its own internal SIGSEGV listener for wasm OOB optimization things. Instead of using `sigaction`, you should use `node::RegisterSignalHandler`

**Comment by raub** [comment]
Hello, thanks for the suggestion. That initially looked promising, and I tried it.
`error: ‘RegisterSignalHandler’ is not a member of ‘node’`
That is LTS Node 12.18.3. If I didn't miss anything.

Also: V8 and Node are quite different things. Consider the fact Node is able to run on a different engine than V8. And node-api is the third separate thing.

Even if (in October) with Node 14 (LTS by then) that finally works... That also means it loses compatibility with Node 12 immediately. This is not what I want or expect. This addon is distributed in binary form and it **must** be ABI compatible across at least several major versions of Node.

The code itself I found here https://github.com/nodejs/node/blob/54746bb763ebea0dc7e99d88ff4b379bcd680964/src/node.cc#L531 seems to be pretty similar to the current code in this repo. Except for WASM condition part. But in general (including cases when V8 is not your engine of choice), there is no reason to think something is going to fail more than SIGSEGV itself.

So for now I'll have to leave it as-is. If Node Team adds a node-api method for this matter, and backports it to the previous releases (which I doubt), we can return to this topic later.
