### ISSUE TITLE
support for Macos-arm64

### ISSUE THREAD

**Issue by fusionbeam** [node-3d/segfault-raub#11]
Hi,

I'm indirectly using this module through iohook-raaub. 
Executions are failing with this error:
```
Error: Cannot find module './bin-darwin-arm64/segfault'
Require stack:
- /Users/ra/code/treelet/treelet-desktop-app/node_modules/segfault-raub/index.js
- /Users/ra/code/treelet/treelet-desktop-app/node_modules/iohook-raub/core.js
- /Users/ra/code/treelet/treelet-desktop-app/node_modules/iohook-raub/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
```

How can we add support for Mac with M chips?

Thanks,
Rares

**Comment by raub** [comment]
Added a new binary for MacOS ARM https://github.com/node-3d/segfault-raub/releases/tag/2.3.0 - please check if it works if you can (I don't have a mac to do so).

**Comment by fusionbeam** [comment]
working. thank you.
