### ISSUE TITLE
Unable to package a project dependent on segfault-raub using esbuild

### ISSUE THREAD

**Issue by epessoa-i** [node-3d/segfault-raub#12]
Hello,
Thank you very much for maintaining segfault-raub. 

When running esbuild to compile a .cjs script prior to packaging my project, esbuild does not recognize the module as native and complains it can't find the module. Adding ".node" to the require call solves the issue.

To make your work easier, I'll go ahead and submit a pull request adding this.

**Comment by raub** [comment]
Hello, thank you for the contribution! I will consider adding ".node" exts to all addon imports then.

**Comment by raub** [comment]
Published as [3.0.1](https://www.npmjs.com/package/segfault-raub). Also, [source link](https://github.com/node-3d/segfault-raub/blob/3.0.1/index.js#L9).
