### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by jcayzac** [node-3d/segfault-raub#15]
`Cannot find module './bin-darwin-arm64/segfault'`

**Comment by raub** [comment]
Hello.

1. Did you have any issues during installation? Noscript? Reinstalled?
2. Did end up having the `node_modules/segfault-raub/bin-darwin-arm64/segfault.node` file?
3. If there is no such file on your system, try adding it manually from [here](https://github.com/node-3d/segfault-raub/releases/tag/2.3.0).

**Comment by raub** [comment]
We can reopen this later, if the issue persists and if you are able to provide more context related to its possible origin. Please try [installing the latest version](https://www.npmjs.com/package/segfault-raub) and refer to the tips above.
