### ISSUE TITLE
Support for aarch64 (linux)

### ISSUE THREAD

**Issue by logidelic** [node-3d/segfault-raub#7]
Hello!

I tried to use this addon on aarch64 and get an error when trying to require the module ("cannot open shared object file"). I'm assuming that this is because the module is pre-compiled.

How can I build the module myself? Any reason it's not built dynamically during npm install?

Thanks!

**Comment by Zorlin** [comment]
This is huge for me, I'm trying to debug a segfault on aarch64 and the original node-segfault-handler is not providing any useful output. I wanted to try this one, but if it isn't working on aarch64 it won't help :(

**Comment by raub** [comment]
Hello. The reason this module is not built dynamically is that I don't want to force people into installing Python and other build tools as a prerequisite. To build it dynamically, it is possible to use `npm run build` or the same `cd src && node-gyp rebuild`.

The prebuilt binaries are produced within GitHub action environments specified in workflows https://github.com/node-3d/segfault-raub/tree/master/.github/workflows

**Comment by raub** [comment]
https://amperecomputing.com/blogs/adding-aarch64-to-your-github-ci-with-github-actions-and-ampere-altra.html seems to be possible to prebuild aarch64 binaries with Oracle Cloud, I will research that

**Comment by raub** [comment]
The latest `segfault-raub@2.0.0` supports Linux Aarch64.
